apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xgny1qkdq-nodejs 
  janus-idp.io/tekton: xgny1qkdq-nodejs
  backstage.io/kubernetes-id: xgny1qkdq-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xgny1qkdq-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml