apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xgny1qkdq-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xgny1qkdq-nodejs 
  name: xgny1qkdq-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xgny1qkdq-nodejs 
